[package]
name = "sp-node-permission"
version = "2.0.0-rc5"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Node permission primitives"
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", default-features = false, version = "1.3.1" }
sp-api = { version = "2.0.0-rc5", default-features = false, path = "../api" }
sp-application-crypto = { version = "2.0.0-rc5", default-features = false, path = "../application-crypto" }
sp-core = { version = "2.0.0-rc5", default-features = false, path = "../core" }
sp-runtime = { version = "2.0.0-rc5", default-features = false, path = "../runtime" }
sp-std = { version = "2.0.0-rc5", default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-api/std",
	"sp-application-crypto/std",
    "sp-core/std",
	"sp-runtime/std",
    "sp-std/std",
]
