[package]
name = "pallet-node-authorization"
version = "2.0.0-rc5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for node authorization"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
frame-support = { version = "2.0.0-rc5", default-features = false, path = "../support" }
frame-system = { version = "2.0.0-rc5", default-features = false, path = "../system" }
sp-core = { version = "2.0.0-rc5", default-features = false, path = "../../primitives/core" }
sp-io = { version = "2.0.0-rc5", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "2.0.0-rc5", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "2.0.0-rc5", default-features = false, path = "../../primitives/std" }

[dev-dependencies]
hex-literal = "0.2.1"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
